project_id = "putxlbycbcwtfzhhkmzg"

[functions.ai-coach]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.process-referral]
verify_jwt = false

[functions.download-data]
verify_jwt = false

[functions.delete-incomplete-signup]
verify_jwt = false

[functions.send-payment-confirmation]
verify_jwt = false
