project_id = "putxlbycbcwtfzhhkmzg"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.ai-coach]
verify_jwt = false